### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by KarolS** [recruit-tech/redpen#353]
As in the title. It would be nice (although very hard to do, I guess) if Redpen could check TeX input files.

**Comment by takahi-i** [comment]
The work on LaTex support is going to be merged in few months. 
We can see the progress in #438.

**Comment by takahi-i** [comment]
Hi @KarolS.  LaTeX support was merged with #438.  I will close this issue.

**Comment by KarolS** [comment]
Thank you.

**Comment by takahi-i** [comment]
:-)
