### ISSUE TITLE
homebrew formula

### ISSUE THREAD

**Issue by kozo2** [recruit-tech/redpen#362]
I sent a pull request(redpen formula) to homebrew.

https://github.com/Homebrew/homebrew/pull/35147

I would like you to

1. remove "experimental" suffix from release filename
2. remove "-cli" suffix from release filename
3. update version (for "redpen --version" command, currently the output is 0.6)

**Comment by takahi-i** [comment]
This issue was closed since the redpen formula was merged. Thank you very much @kozo2!
