### ISSUE TITLE
Create single package containing command and server

### ISSUE THREAD

**Issue by takahi-i** [recruit-tech/redpen#371]
Currently the RedPen build process creates two packages redpen-cli.tar.gz and redpen-server.war, but I think the final package should be merged into one. I will modifiy the RedPen build process to  merge the packages.

**Comment by akinomurasame** [comment]
Personally, I agree.

For example, When I use -d option, RedPen is starting server mode. And other option is CLI mode.

    $ redpen -d
    starting server process...done.
    $ redpen -c conf.xml target.txt
    17:02:38.367 [main] INFO  cc.redpen.Configura....

Is it like this?

**Comment by takahi-i** [comment]
Thank you a lot for the comment! One command supports both comand and server is a good idea, but maybe the command should be handled in another issue (such as "Make the redpen command support server") in order to make the the modification small.

**Comment by akinomurasame** [comment]
Thank you for your follow-up. I was able to understand!

**Comment by takahi-i** [comment]
This issue is going to be done with #371

**Comment by takahi-i** [comment]
Fix with #450
