### ISSUE TITLE
Add all in one package

### ISSUE THREAD

**Issue by takahi-i** [recruit-tech/redpen#429]
The package containing both cli and war file are included. 

The following is the image of directory structure.

```
/bin/redpen
/bin/redpen.war
/lib/jar-files.
```

**Comment by yusuke** [comment]
the war file contains all libraries.
Is /lib/* necessary?

**Comment by takahi-i** [comment]
Thank you for the comment @yusuke!

> the war file contains all libraries.
Right maybe adding redpen.war to /bin/ directory in the redpen pacakge.

> Is /lib/* necessary?
Currently /lib/ is needed to run redpen cli. maybe the redpen-cli jar should contains all the jar files as redpen.war.

**Comment by takahi-i** [comment]
Fixed with #450
