### ISSUE TITLE
AsciiDoc parser

### ISSUE THREAD

**Issue by takahi-i** [recruit-tech/redpen#432]

**Comment by gerryhocks** [comment]
Thanks for assigning this task - been busy over the last few days but will start on this today.

**Comment by takahi-i** [comment]
Thank you very much but do not work too hard :)

**Comment by takahi-i** [comment]
Merged #444. I will add tests for AsciiDoc parser before the v1.3 release.

**Comment by takahi-i** [comment]
Fixed with PR #459
