### ISSUE TITLE
Reduce server memory usage in Heroku envrionment

### ISSUE THREAD

**Issue by takahi-i** [recruit-tech/redpen#449]
I got a report that RedPen server consumes over 600 MB memory. I would like to investigate the reason and reduce the memory usage if possible.

**Comment by gerryhocks** [comment]
I imagine the addition of JRuby's runtime to support AsciiDoctor might have increased the memory usage.

I will look at options to reduce it (as we don't need too much).

Do we have an idea of a target amount of memory we should aim for?

**Comment by takahi-i** [comment]
Thank you very much the comment @gerryhocks!

Current target amount of memory is 512MB since the amount is the memory size of common Heroku boxes.

https://devcenter.heroku.com/articles/dyno-types#available-dyno-types

**Comment by gerryhocks** [comment]
Understood! Thanks for the info!

**Comment by gerryhocks** [comment]
I've had a little bit of a look into this. I am finding that if I try:
```
MAVEN_OPTS="-Xmx256m" mvn jetty:run
```
then the server runs fine. I can parse some documents, including AsciiDoc, and it tells me it has used 113M.

I was hoping therefore, for the issue reported, when deploying to Heroku, we could find out what options were set (eg: JAVA_OPTS) and what command was executed?

**Comment by takahi-i** [comment]
Excellent! Thank very much for the investigation @gerryhocks!

**Comment by yusuke** [comment]
The original reporter says that he hasn't seen any OutOfMemoryError.
https://twitter.com/yusuke/status/618625027894738944
https://twitter.com/yusuke/status/618625501913968641

I think we can close this issue for now.

**Comment by takahi-i** [comment]
Thank you very much @yusuke! I will close this issue. When we get a report on OutOfMemoryError I will create another issue.
