### ISSUE TITLE
Doubled Negative Validator

### ISSUE THREAD

**Issue by takahi-i** [recruit-tech/redpen#461]
This validator check input sentence contains doubled negative expression.

The following example contains doubled negative expression.

**Unless** the input sentence is **not** contains the word.

**Comment by takahi-i** [comment]
#467 provides  doubled negative validation for English and Japanese.

**Comment by gerryhocks** [comment]
Looks nice! I would perhaps change the English test sentence:

 "We believe it, unless not that is true"

to

 "We believe it, unless it is not true"

**Comment by takahi-i** [comment]
Thank you very much for the comment @gerryhocks! I will fix before the merge.

**Comment by takahi-i** [comment]
Fixed with #467.
