### ISSUE TITLE
false detection of KatakanaSpellCheck

### ISSUE THREAD

**Issue by kubosho** [recruit-tech/redpen#464]
## actual

https://twitter.com/kubosho_/status/626064491470413824

> ValidationError[KatakanaSpellCheck], カタカナ単語 "エンジニア" に類似する単語 "エンジン" が行 "90" でみつかりました。

## expect

No error.

**Comment by takahi-i** [comment]
Thank you very much for reporting the issue @kubosho!

**Comment by takahi-i** [comment]
To be honest, fixing all the problems that the valid Katakana words are reported as misspelled katakana words is very difficult. But there are three enhancements to suppress most of such cases.

* *register the valid katakana words into the default dictionary:*  currently only less than 100 words are registered as the default dictionary (https://github.com/recruit-tech/redpen/blob/master/redpen-core/src/main/resources/default-resources/katakana/katakana-spellcheck.dat) . We can suppress many cases adding the valid katakana words  into the dictionary
* **setting minimum threshold** if the katakana words are common in the input documents, the word seems not to be invalid. In this workaround we add the threshold which specify the frequency. Katakanaspellvalidator suppresses the error when the word frequency is over the specified minimum frequency.
* **Add user dictionary**

I will try the enhancement

**Comment by kubosho** [comment]
:+1:

**Comment by takahi-i** [comment]
Hello @kubosho. I have merged the enhancements of KatakanaSpellCheck with #469. It would be appreciate it if you try the validator in your environment when you have a time. 

When there are other problems, please let us know adding the  new issues.

**Comment by takahi-i** [comment]
I will fix this issue. When katakanaspellcheck still has another issue. We will create another issue or reopen this issue.

**Comment by takahi-i** [comment]
The attributes supported with this enhancement are described in the latest document   http://redpen.cc/docs/latest/validator.html

**Comment by kubosho** [comment]
@takahi-i 
Thanks! I'll check for an update.
